# This workflow will install two versions of Python on ubuntu,
# install MethSCAn and its dependencies,
# check for syntax errors etc with the linter Ruff,
# and run all tests.

name: Install, lint, test.

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"  # cache dependencies
    - name: Install MethSCAn and dependencies
      run: |
        python -m pip install --upgrade pip pytest
        pip install .
    - name: Lint with Ruff
      uses: chartboost/ruff-action@v1
    - name: Test with pytest
      run: |
        pytest
